// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AddingGenreAndOtherParameterToMovies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingGenreAndOtherParameterToMovies));
        
        string IMigrationMetadata.Id
        {
            get { return "201807281152135_AddingGenreAndOtherParameterToMovies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
